# Generated by Django 4.1.7 on 2023-03-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrs_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='Gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], default='male', max_length=20),
        ),
    ]
