# Generated by Django 4.1.7 on 2023-04-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrs_app', '0002_lecturer_is_active_alter_lecturer_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='name',
        ),
        migrations.AddField(
            model_name='admin',
            name='department',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
