# Generated by Django 4.1.7 on 2023-03-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrs_app', '0003_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (2, 'lecturer'), (3, 'student')], default=1, max_length=10),
        ),
    ]
