# Generated by Django 4.1.7 on 2023-03-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrs_app', '0006_customuser_gender_alter_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='Gender',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
