# Generated by Django 4.1.7 on 2023-03-27 09:49

from django.db import migrations, models
import lrs_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('lrs_app', '0008_rename_gender_lecturer_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, validators=[lrs_app.models.max_length]),
        ),
    ]
