# Generated by Django 4.1.7 on 2023-03-27 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lrs_app', '0009_lecturer_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='body',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='lecturer_id',
            new_name='lecturer',
        ),
    ]
