# Generated by Django 4.1.7 on 2023-03-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrs_app', '0010_rename_body_review_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
