# Generated by Django 4.1.7 on 2023-03-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrs_app', '0011_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
