# Generated by Django 4.1.7 on 2023-03-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrs_app', '0012_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(max_length=5),
        ),
    ]
