# Generated by Django 4.1.7 on 2023-04-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrs_app', '0016_student_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'admin'), ('lecturer', 'lecturer'), ('student', 'student')], default='HOD', max_length=10),
        ),
    ]
