# Generated by Django 4.1.7 on 2023-04-04 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lrs_app', '0018_remove_lecturer_email_remove_lecturer_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='matric_no',
            new_name='matricno',
        ),
    ]
