# Generated by Django 4.1.7 on 2023-04-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrs_app', '0023_alter_customuser_gender_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='Gender',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='firstname',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='lastname',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
