# Generated by Django 4.1.7 on 2023-04-04 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lrs_app', '0024_lecturer_gender_lecturer_email_lecturer_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturer',
            old_name='Gender',
            new_name='gender',
        ),
    ]
