# Generated by Django 4.1.7 on 2023-04-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrs_app', '0026_rename_firstname_lecturer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
