# Generated by Django 4.1.7 on 2023-04-05 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lrs_app', '0029_alter_lecturer_id_alter_review_id_alter_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='last_name',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
