# Generated by Django 4.1.7 on 2023-04-09 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lrs_app', '0035_alter_review_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='student',
        ),
    ]
